Declare github_user variable in main.tf
Plan was failing as github_user variable wasn't defined.

Error: Reference to undeclared input variable

  on main.tf line 47, in resource "oci_core_instance" "oracle-arm":
  47:           github_user = var.github_user,

An input variable with the name "github_user" has not been declared. This variable can be declared with a variable "github_user" {} block.